export const ERROR_CATALOG = {
  MALFORMED_REQUEST: 400,
  VALIDATION_ERROR: 400,
  INVALID_TOPIC_ORDER: 400,
  UNAUTHENTICATED: 401,
  SESSION_EXPIRED: 401,
  INVALID_WEBHOOK_SIGNATURE: 401,
  FORBIDDEN: 403,
  ROUTE_NOT_FOUND: 404,
  PRODUCT_NOT_FOUND: 404,
  TOPIC_NOT_FOUND: 404,
  REVIEW_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  PRODUCT_NOT_VOTABLE: 409,
  TOPIC_ALREADY_EXISTS: 409,
  TOPIC_IN_USE: 409,
  IMAGE_TOO_LARGE: 413,
  UNSUPPORTED_IMAGE_TYPE: 415,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  UPSTREAM_ERROR: 502,
  SERVICE_UNAVAILABLE: 503,
} as const;

export type ErrorCode = keyof typeof ERROR_CATALOG;

export function statusFor(code: string): number {
  return code in ERROR_CATALOG ? ERROR_CATALOG[code as ErrorCode] : ERROR_CATALOG.INTERNAL_ERROR;
}
